//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRC.Global.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRC.Global.View.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made changes to this port.  Are you sure you want to cancel and lose those changes?.
        /// </summary>
        internal static string strCancelEditingPortAreYouSure {
            get {
                return ResourceManager.GetString("strCancelEditingPortAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard your changes?.
        /// </summary>
        internal static string strCancelEditingPortTitle {
            get {
                return ResourceManager.GetString("strCancelEditingPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this server domain?.
        /// </summary>
        internal static string strDelServerDomainAreYouSure {
            get {
                return ResourceManager.GetString("strDelServerDomainAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this server domain?.
        /// </summary>
        internal static string strDelServerDomainAreYouSureTitle {
            get {
                return ResourceManager.GetString("strDelServerDomainAreYouSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re adding a new network.
        /// </summary>
        internal static string strNetworkEditorAddingTitle {
            get {
                return ResourceManager.GetString("strNetworkEditorAddingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made changes to this network.  Are you sure you want to discard those?.
        /// </summary>
        internal static string strNetworkEditorCancelChanges {
            get {
                return ResourceManager.GetString("strNetworkEditorCancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard your changes?.
        /// </summary>
        internal static string strNetworkEditorCancelChangesTitle {
            get {
                return ResourceManager.GetString("strNetworkEditorCancelChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re editing the network ”{1}“ which was orignally called ”{2}“..
        /// </summary>
        internal static string strNetworkEditorEditingTitle {
            get {
                return ResourceManager.GetString("strNetworkEditorEditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re adding a new port.
        /// </summary>
        internal static string strPortEditorTitleAddingMode {
            get {
                return ResourceManager.GetString("strPortEditorTitleAddingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re editing a port that started out as {1}.
        /// </summary>
        internal static string strPortEditorTitleEditingMode {
            get {
                return ResourceManager.GetString("strPortEditorTitleEditingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re adding a SSL prot.
        /// </summary>
        internal static string strPortEditorTitleSslAddingMode {
            get {
                return ResourceManager.GetString("strPortEditorTitleSslAddingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re editing an SSL port that started out as {1}.
        /// </summary>
        internal static string strPortEditorTitleSslEditingMode {
            get {
                return ResourceManager.GetString("strPortEditorTitleSslEditingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter at least one domain name..
        /// </summary>
        internal static string strValidationEnterAtLeastOneDomainName {
            get {
                return ResourceManager.GetString("strValidationEnterAtLeastOneDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a homepage, “{1}”, but it isn&apos;t a valid URI.  Please fix it or clear the field..
        /// </summary>
        internal static string strValidationHomepageUriNotValid {
            get {
                return ResourceManager.GetString("strValidationHomepageUriNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must name this network.  The current name is blank..
        /// </summary>
        internal static string strValidationNameBlank {
            get {
                return ResourceManager.GetString("strValidationNameBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name “{1}” is in use.  Please choose another..
        /// </summary>
        internal static string strValidationNameTaken {
            get {
                return ResourceManager.GetString("strValidationNameTaken", resourceCulture);
            }
        }
    }
}
