//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestChat.IRC.Data.Defs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestChat.IRC.Data.Defs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string strBoolModeStateOffDesc {
            get {
                return ResourceManager.GetString("strBoolModeStateOffDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string strBoolModeStateOnDesc {
            get {
                return ResourceManager.GetString("strBoolModeStateOnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtTheme.
        /// </summary>
        internal static string strChanServOptAtTheme {
            get {
                return ResourceManager.GetString("strChanServOptAtTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChanServ is implemented by AtTheme.  Only select this if you&apos;re sure that&apos;s what they use..
        /// </summary>
        internal static string strChanServOptAtThemeToolTip {
            get {
                return ResourceManager.GetString("strChanServOptAtThemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None available.
        /// </summary>
        internal static string strChanServOptNull {
            get {
                return ResourceManager.GetString("strChanServOptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network doesn&apos;t have ChanServ.
        /// </summary>
        internal static string strChanServOptNullToolTip {
            get {
                return ResourceManager.GetString("strChanServOptNullToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available, but type unknown.
        /// </summary>
        internal static string strChanServOptUnknown {
            get {
                return ResourceManager.GetString("strChanServOptUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network has a ChanServ, but you don&apos;t know much about it.
        /// </summary>
        internal static string strChanServOptUnknownToolTip {
            get {
                return ResourceManager.GetString("strChanServOptUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join throttling to be sent to another channel..
        /// </summary>
        internal static string strDefChanModeForwardDesc {
            get {
                return ResourceManager.GetString("strDefChanModeForwardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the channel you want the forward to go to..
        /// </summary>
        internal static string strDefChanModeForwardDestParamDesc {
            get {
                return ResourceManager.GetString("strDefChanModeForwardDestParamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string strDefChanModeForwardDetParamName {
            get {
                return ResourceManager.GetString("strDefChanModeForwardDetParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode causes the channel to be invite only.  People must get an invite via either the ChanServ/Q&apos;s invite function or the |/invite| command..
        /// </summary>
        internal static string strDefChanModeInviteOnlyDesc {
            get {
                return ResourceManager.GetString("strDefChanModeInviteOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting a key requires anyone who wants to join to enter a key in order to join..
        /// </summary>
        internal static string strDefChanModeKeyDesc {
            get {
                return ResourceManager.GetString("strDefChanModeKeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the key for this channel.
        /// </summary>
        internal static string strDefChanModeKeyParamDesc {
            get {
                return ResourceManager.GetString("strDefChanModeKeyParamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string strDefChanModeKeyParamName {
            get {
                return ResourceManager.GetString("strDefChanModeKeyParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this mode is on, only users with op, half-op, or voice may talk in the channel..
        /// </summary>
        internal static string strDefChanModeModDesc {
            get {
                return ResourceManager.GetString("strDefChanModeModDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode causes colors to be stripped.
        /// </summary>
        internal static string strDefChanModeNoColorDesc {
            get {
                return ResourceManager.GetString("strDefChanModeNoColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode prevents messages from being set from outside the channel.  When set, users or bots must be in the channel to post..
        /// </summary>
        internal static string strDefChanModeNoExternMsgDesc {
            get {
                return ResourceManager.GetString("strDefChanModeNoExternMsgDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this mode is set, all posts from anyone without voice or op privileges are sent to ops instead of the channel as a whole..
        /// </summary>
        internal static string strDefChanModeOpsModDesc {
            get {
                return ResourceManager.GetString("strDefChanModeOpsModDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private channels disable |/knock|..
        /// </summary>
        internal static string strDefChanModePrivateDesc {
            get {
                return ResourceManager.GetString("strDefChanModePrivateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode, when set, prevents users who aren&apos;t registered from joining.  If you set this, be sure to set a forwarding location with &apos;f&apos;..
        /// </summary>
        internal static string strDefChanModeRegisteredUserOnlyDesc {
            get {
                return ResourceManager.GetString("strDefChanModeRegisteredUserOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this mode is set, the channel won&apos;t be listed in |/whois| or |/list|..
        /// </summary>
        internal static string strDefChanModeSecretDesc {
            get {
                return ResourceManager.GetString("strDefChanModeSecretDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mode prevents changes to the topic by users who aren&apos;t ops or half ops.  Note: Services like ChanServ or Q may prevent such topic changes even if this mode is off..
        /// </summary>
        internal static string strDefChanModeTopicLockDesc {
            get {
                return ResourceManager.GetString("strDefChanModeTopicLockDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designates this client as “invisible”..
        /// </summary>
        internal static string strDefUserModeInvisibleDesc {
            get {
                return ResourceManager.GetString("strDefUserModeInvisibleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designates the user as a IRC operator.  Use |/oper| to obtain this..
        /// </summary>
        internal static string strDefUserModeIrcOpDesc {
            get {
                return ResourceManager.GetString("strDefUserModeIrcOpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents users not in your |/accept| list from messaging you and inviting you to channels.
        /// </summary>
        internal static string strDefUserModeMsgRestrictDesc {
            get {
                return ResourceManager.GetString("strDefUserModeMsgRestrictDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent users not on your |/accept| list and not in a channel with you from messaging you or inviting you to channels.  This is a softer form of +g..
        /// </summary>
        internal static string strDefUserModeMsgRestrictSoftDesc {
            get {
                return ResourceManager.GetString("strDefUserModeMsgRestrictSoftDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents unidentified users that you haven&apos;t accepted from messaging you..
        /// </summary>
        internal static string strDefUserModeRestrictMsgUnidentUsersDesc {
            get {
                return ResourceManager.GetString("strDefUserModeRestrictMsgUnidentUsersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can see wallops.
        /// </summary>
        internal static string strDefUserModeWallopsDesc {
            get {
                return ResourceManager.GetString("strDefUserModeWallopsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False / Not Available.
        /// </summary>
        internal static string strHasAlisFalse {
            get {
                return ResourceManager.GetString("strHasAlisFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ALIS is present on this network.
        /// </summary>
        internal static string strHasAlisFalseToolTip {
            get {
                return ResourceManager.GetString("strHasAlisFalseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True / Available.
        /// </summary>
        internal static string strHasAlisTrue {
            get {
                return ResourceManager.GetString("strHasAlisTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIS is available and ready to use..
        /// </summary>
        internal static string strHasAlisTrueToolTip {
            get {
                return ResourceManager.GetString("strHasAlisTrueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string strHasAlisUnknown {
            get {
                return ResourceManager.GetString("strHasAlisUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIS may or may not be present.
        /// </summary>
        internal static string strHasAlisUnknownToolTip {
            get {
                return ResourceManager.GetString("strHasAlisUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False / Not Available.
        /// </summary>
        internal static string strHasQFalse {
            get {
                return ResourceManager.GetString("strHasQFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Q present on this network.  Q is really only QuakeNet..
        /// </summary>
        internal static string strHasQFalseToolTip {
            get {
                return ResourceManager.GetString("strHasQFalseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True / Available.
        /// </summary>
        internal static string strHasQTrue {
            get {
                return ResourceManager.GetString("strHasQTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q is present.
        /// </summary>
        internal static string strHasQTrueToolTip {
            get {
                return ResourceManager.GetString("strHasQTrueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string strHasQUnknown {
            get {
                return ResourceManager.GetString("strHasQUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q might or might not be present on this network.
        /// </summary>
        internal static string strHasQUnknownToolTip {
            get {
                return ResourceManager.GetString("strHasQUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in manually.
        /// </summary>
        internal static string strManual {
            get {
                return ResourceManager.GetString("strManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom/User defined.
        /// </summary>
        internal static string strNetworkInfoTypeCustom {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network created by the user and not based on another network..
        /// </summary>
        internal static string strNetworkInfoTypeCustomToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeCustomToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string strNetworkInfoTypeHidden {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network provided by Best Chat, but the user has chosen to hide the network from views.
        /// </summary>
        internal static string strNetworkInfoTypeHiddenToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeHiddenToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string strNetworkInfoTypeModified {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network whose information was originally provided by Best Chat, but the user has made changes..
        /// </summary>
        internal static string strNetworkInfoTypeModifiedToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeModifiedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined.
        /// </summary>
        internal static string strNetworkInfoTypePredefined {
            get {
                return ResourceManager.GetString("strNetworkInfoTypePredefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network whose information is provided by Best Chat and hasn&apos;t been changed..
        /// </summary>
        internal static string strNetworkInfoTypePredefinedToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypePredefinedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use NickServ (Requires a network that provides NickServ).
        /// </summary>
        internal static string strNickServ {
            get {
                return ResourceManager.GetString("strNickServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtTheme.
        /// </summary>
        internal static string strNickServOptAtTheme {
            get {
                return ResourceManager.GetString("strNickServOptAtTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickServ is implemented by AtTheme.  Only select this if you&apos;re sure that&apos;s what they use..
        /// </summary>
        internal static string strNickServOptAtThemeToolTip {
            get {
                return ResourceManager.GetString("strNickServOptAtThemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None available.
        /// </summary>
        internal static string strNickServOptNull {
            get {
                return ResourceManager.GetString("strNickServOptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network doesn&apos;t have NickServ.
        /// </summary>
        internal static string strNickServOptNullToolTip {
            get {
                return ResourceManager.GetString("strNickServOptNullToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available, but type unknown.
        /// </summary>
        internal static string strNickServOptUnknown {
            get {
                return ResourceManager.GetString("strNickServOptUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network has a NickServ, but you don&apos;t know much about it.
        /// </summary>
        internal static string strNickServOptUnknownToolTip {
            get {
                return ResourceManager.GetString("strNickServOptUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SASL.
        /// </summary>
        internal static string strSASL {
            get {
                return ResourceManager.GetString("strSASL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChanServ is preventing this mode from being set..
        /// </summary>
        internal static string strThreeWayModeStateForcedOff {
            get {
                return ResourceManager.GetString("strThreeWayModeStateForcedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChanServ is ensuring this mode is set.
        /// </summary>
        internal static string strThreeWayModeStateLockedOnDesc {
            get {
                return ResourceManager.GetString("strThreeWayModeStateLockedOnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChanServ isn&apos;t controlling this mode.
        /// </summary>
        internal static string strThreeWayModeStateNoPrefDesc {
            get {
                return ResourceManager.GetString("strThreeWayModeStateNoPrefDesc", resourceCulture);
            }
        }
    }
}
