//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestChat.IRC.Data.Defs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestChat.IRC.Data.Defs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtTheme.
        /// </summary>
        internal static string strChanServOptAtTheme {
            get {
                return ResourceManager.GetString("strChanServOptAtTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChanServ is implemented by AtTheme.  Only select this if you&apos;re sure that&apos;s what they use..
        /// </summary>
        internal static string strChanServOptAtThemeToolTip {
            get {
                return ResourceManager.GetString("strChanServOptAtThemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None available.
        /// </summary>
        internal static string strChanServOptNull {
            get {
                return ResourceManager.GetString("strChanServOptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network doesn&apos;t have ChanServ.
        /// </summary>
        internal static string strChanServOptNullToolTip {
            get {
                return ResourceManager.GetString("strChanServOptNullToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available, but type unknown.
        /// </summary>
        internal static string strChanServOptUnknown {
            get {
                return ResourceManager.GetString("strChanServOptUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network has a ChanServ, but you don&apos;t know much about it.
        /// </summary>
        internal static string strChanServOptUnknownToolTip {
            get {
                return ResourceManager.GetString("strChanServOptUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False / Not Available.
        /// </summary>
        internal static string strHasAlisFalse {
            get {
                return ResourceManager.GetString("strHasAlisFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ALIS is present on this network.
        /// </summary>
        internal static string strHasAlisFalseToolTip {
            get {
                return ResourceManager.GetString("strHasAlisFalseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True / Available.
        /// </summary>
        internal static string strHasAlisTrue {
            get {
                return ResourceManager.GetString("strHasAlisTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIS is available and ready to use..
        /// </summary>
        internal static string strHasAlisTrueToolTip {
            get {
                return ResourceManager.GetString("strHasAlisTrueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string strHasAlisUnknown {
            get {
                return ResourceManager.GetString("strHasAlisUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIS may or may not be present.
        /// </summary>
        internal static string strHasAlisUnknownToolTip {
            get {
                return ResourceManager.GetString("strHasAlisUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False / Not Available.
        /// </summary>
        internal static string strHasQFalse {
            get {
                return ResourceManager.GetString("strHasQFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Q present on this network.  Q is really only QuakeNet..
        /// </summary>
        internal static string strHasQFalseToolTip {
            get {
                return ResourceManager.GetString("strHasQFalseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True / Available.
        /// </summary>
        internal static string strHasQTrue {
            get {
                return ResourceManager.GetString("strHasQTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q is present.
        /// </summary>
        internal static string strHasQTrueToolTip {
            get {
                return ResourceManager.GetString("strHasQTrueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string strHasQUnknown {
            get {
                return ResourceManager.GetString("strHasQUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q might or might not be present on this network.
        /// </summary>
        internal static string strHasQUnknownToolTip {
            get {
                return ResourceManager.GetString("strHasQUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in manually.
        /// </summary>
        internal static string strManual {
            get {
                return ResourceManager.GetString("strManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom/User defined.
        /// </summary>
        internal static string strNetworkInfoTypeCustom {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network created by the user and not based on another network..
        /// </summary>
        internal static string strNetworkInfoTypeCustomToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeCustomToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string strNetworkInfoTypeHidden {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network provided by Best Chat, but the user has chosen to hide the network from views.
        /// </summary>
        internal static string strNetworkInfoTypeHiddenToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeHiddenToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string strNetworkInfoTypeModified {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network whose information was originally provided by Best Chat, but the user has made changes..
        /// </summary>
        internal static string strNetworkInfoTypeModifiedToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypeModifiedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined.
        /// </summary>
        internal static string strNetworkInfoTypePredefined {
            get {
                return ResourceManager.GetString("strNetworkInfoTypePredefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network whose information is provided by Best Chat and hasn&apos;t been changed..
        /// </summary>
        internal static string strNetworkInfoTypePredefinedToolTipText {
            get {
                return ResourceManager.GetString("strNetworkInfoTypePredefinedToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use NickServ (Requires a network that provides NickServ).
        /// </summary>
        internal static string strNickServ {
            get {
                return ResourceManager.GetString("strNickServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtTheme.
        /// </summary>
        internal static string strNickServOptAtTheme {
            get {
                return ResourceManager.GetString("strNickServOptAtTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickServ is implemented by AtTheme.  Only select this if you&apos;re sure that&apos;s what they use..
        /// </summary>
        internal static string strNickServOptAtThemeToolTip {
            get {
                return ResourceManager.GetString("strNickServOptAtThemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None available.
        /// </summary>
        internal static string strNickServOptNull {
            get {
                return ResourceManager.GetString("strNickServOptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network doesn&apos;t have NickServ.
        /// </summary>
        internal static string strNickServOptNullToolTip {
            get {
                return ResourceManager.GetString("strNickServOptNullToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available, but type unknown.
        /// </summary>
        internal static string strNickServOptUnknown {
            get {
                return ResourceManager.GetString("strNickServOptUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this if the network has a NickServ, but you don&apos;t know much about it.
        /// </summary>
        internal static string strNickServOptUnknownToolTip {
            get {
                return ResourceManager.GetString("strNickServOptUnknownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SASL.
        /// </summary>
        internal static string strSASL {
            get {
                return ResourceManager.GetString("strSASL", resourceCulture);
            }
        }
    }
}
